# Generated by Django 4.2.7 on 2026-03-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('episodes', models.IntegerField(default=100)),
                ('batch_size', models.IntegerField(default=32)),
                ('initial_cash', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('final_epsilon', models.FloatField(blank=True, null=True)),
                ('total_reward', models.FloatField(blank=True, null=True)),
                ('final_portfolio_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_loss_pct', models.FloatField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, default='', max_length=500)),
                ('tensorboard_log_dir', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='market_data.symbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('step', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.trainingsession')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market_data.symbol')),
            ],
            options={
                'ordering': ['step'],
            },
        ),
    ]
